import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       
        <div className={styles.head}>
          <div className={styles.header}>
            <h1>FUN THINGS ABOUT RACHEL</h1>
          </div>
          <div className={styles.topnav}>
            <a href="#" className={styles.topnavitem} >Home</a>
            <a href="#" className={styles.topnavitem} >Dancing</a>
            <a href="#" className={styles.topnavitem} >Traveling</a>
          </div>
        </div>

        <div className={styles.intro}>
          <h2>A Little About Me</h2>
          <p>Hi, my name is Rachel Qian. I am currently a product designer based in Los Angeles, CA. Scroll down to learn more about my hobbies and interests!</p>
        </div>

        <div className={styles.row}>
          <div className={styles.column}>
            <img src="dancing01.jpg"></img>
          </div>
          <div className={styles.column}>
            <h2>Dancing</h2>
            <br></br>
            <p>Dancing has always been my favorite thing to do outside of school and work. I have tried Jazzfunk, Hiphop and Chreography. My next step is to get more into old school styles like Popping and Locking. Living in LA also gives me one of the best resources in the world in terms of dancing. So thank you LA!</p>
            <br></br>
            <a className={styles.button} href="#">Learn More</a>
          </div>
        </div>
        
        <div className={styles.row}>
          <div className={styles.column}>
            <img src="travel01.jpg"></img>
          </div>
          <div className={styles.column}>
            <h2>Traveling</h2>
            <br></br>
            <p>Although not a fan of flying long distances, I love traveling to different countries and cities. I grew up in China and have been to more than 20 cities in China. I have also traveled to Australia, Japan, Korea and Singapore. My goal for the coming years is to explore europe and South America countries more!</p>
            <br></br>
            <a className={styles.button} href="#">Learn More</a>
          </div>
        </div>

        <div className={styles.footer}>
          <p>Learn more about Rachel's design at <a href="https://www.rachelqian.com/">www.rachelqian.com</a></p>
        </div>

      </main>
    </>
  )
}
