import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Traveling() {
  return (
    <>
      <Head>
        <title>Traveling</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       
        <div className={styles.head}>
          <div className={styles.header}>
            <h1>FUN THINGS ABOUT RACHEL</h1>
          </div>
          <div className={styles.topnav}>
            <a href="#" className={styles.topnavitem} >Home</a>
            <a href="#" className={styles.topnavitem} >Dancing</a>
            <a href="#" className={styles.topnavitem} >Traveling</a>
          </div>
        </div>

        <h1 className={styles.headline}>Here's my travel Logs.</h1>
       
        <div className={styles.row}>
          <div className={styles.column}>
            <img src="travel03.jpg"></img>
          </div>
          <div className={styles.column}>
            <div>
              <h2>Singapore</h2>
              <p>I've been to Singapore twice, once for study purpose, and once to travel.</p>
            </div>
            <div className={styles.textblock}>
              <p className={styles.subtitle}>Food</p>
              <p>Singapore has a lot of delicious and affordable food choices, such as Hainan Chicken, Laksa Noodle, and Chili Crab.</p>
              <br></br>
              <img src="singaporefood01.png"></img>
              <img src="singaporefood02.png"></img>
              <img src="singaporefood03.png"></img>
            </div>
            <div className={styles.textblock}>
              <p className={styles.subtitle}>Wheather</p>
              <p>Wheather is one thing that I don't like about Singapore. The temperature is on the higher end year around. On the other hand, it rains a lot during the raining season.</p>
            </div>
          </div>
        </div>

        <div className={styles.row}>
          <div className={styles.column}>
            <img src="travel04.jpg"></img>
          </div>
          <div className={styles.column}>
            <div>
              <h2>Japan</h2>
              <p>In 2016, before going to college, I went on a trip to Japan with my friends. We went to Tokyo, Kyoto, and Osaka.</p>
            </div>
            <div className={styles.textblock}>
              <p className={styles.subtitle}>Food</p>
              <p>My favorite food in Japan was matcha, especially in Kyoto. During my stay there, I got matcha ice cream every day.</p>
              <img src="matcha1.png"></img>
              <img src="matcha2.png"></img>
              <img src="matcha3.png"></img>
            </div>
            <div className={styles.textblock}>
              <p className={styles.subtitle}>Wheather</p>
              <p>I went to Japan the end of April. It was at the end of the cherry blossom season. I was luck enough to see some cherry blossoms.</p>
            </div>
          </div>
        </div>


        <div className={styles.footer}>
          <p>Learn more about Rachel's design at <a href="https://www.rachelqian.com/">www.rachelqian.com</a></p>
        </div>

      </main>
    </>
  )
}
